# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KatapultCli < Formula
  desc "The official CLI for Katapult."
  homepage ""
  version "0.1.0-rc.8"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.8/katapult-cli_0.1.0-rc.8_Darwin_x86_64.tar.gz"
      sha256 "a8fa43799465783e741b5b273e7845a651021338fceca1a99c7e784846e5a818"
    end
    if Hardware::CPU.arm?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.8/katapult-cli_0.1.0-rc.8_Darwin_arm64.tar.gz"
      sha256 "693493e7520e60f065d359b1eef66c2e9e4aa41f2424177d732d34aa3261a24e"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.8/katapult-cli_0.1.0-rc.8_Linux_x86_64.tar.gz"
      sha256 "5aa2bb8d750a5c8a336ff9935a43ce1cd89be914ed00662c461683186e33ef06"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.8/katapult-cli_0.1.0-rc.8_Linux_arm64.tar.gz"
      sha256 "bd1e6e36254be24290ba26351865429163670e5936e629a8851b9c7c909a7ed7"
    end
  end

  def install
    bin.install "katapult"
  end

  test do
    system "#{bin}/katapult version"
  end
end
