# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KatapultCli < Formula
  desc "The official CLI for Katapult."
  homepage ""
  version "0.1.0-rc.9"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.9/katapult-cli_0.1.0-rc.9_Darwin_x86_64.tar.gz"
      sha256 "82799dea4f0fc962bccdabe1cc62ecac03d7f5edd549e934e177a7390f8673bf"
    end
    if Hardware::CPU.arm?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.9/katapult-cli_0.1.0-rc.9_Darwin_arm64.tar.gz"
      sha256 "dee4036240ab9a7cd4f747d462c169409fa14e38e0f3b59f60e39f02470a319f"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.9/katapult-cli_0.1.0-rc.9_Linux_x86_64.tar.gz"
      sha256 "2ec383ea9d68dfbfda127757a805ddb9f49bde6b969ef9910df76d43a824b322"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/krystal/katapult-cli/releases/download/v0.1.0-rc.9/katapult-cli_0.1.0-rc.9_Linux_arm64.tar.gz"
      sha256 "5ca744b793c7ea22f1246fbd06e27a10a1583076b654f097aa72e7a1ee63bf31"
    end
  end

  def install
    bin.install "katapult"
  end

  test do
    system "#{bin}/katapult version"
  end
end
